import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { eq, and, desc, asc } from "@teamcord/db";
import { wikiPages, wikiPageHistory, channels, workspaceMembers, users } from "@teamcord/db";
import { nanoid } from "nanoid";

const updateWikiSchema = z.object({
  title: z.string().min(1).max(200).optional(),
  content: z.string().max(50000), // 50KB max
});

export async function wikiRoutes(app: FastifyInstance) {
  app.addHook("preHandler", app.authenticate);

  // GET /api/v1/channels/:channelId/wiki - Get channel wiki page
  app.get("/channels/:channelId/wiki", async (request, reply) => {
    const db = (app as any).db;
    const { sub: userId } = request.user as { sub: string };
    const { channelId } = request.params as { channelId: string };

    // Check channel exists
    const [channel] = await db
      .select()
      .from(channels)
      .where(eq(channels.id, channelId))
      .limit(1);

    if (!channel) {
      return reply.status(404).send({ error: "Channel not found", statusCode: 404 });
    }

    // Check workspace membership
    const [member] = await db
      .select()
      .from(workspaceMembers)
      .where(
        and(
          eq(workspaceMembers.workspaceId, channel.workspaceId),
          eq(workspaceMembers.userId, userId)
        )
      )
      .limit(1);

    if (!member) {
      return reply.status(403).send({ error: "Forbidden", statusCode: 403 });
    }

    // Get current wiki page
    const [wiki] = await db
      .select({
        id: wikiPages.id,
        channelId: wikiPages.channelId,
        title: wikiPages.title,
        content: wikiPages.content,
        version: wikiPages.version,
        isAutoGenerated: wikiPages.isAutoGenerated,
        createdAt: wikiPages.createdAt,
        updatedAt: wikiPages.updatedAt,
        createdById: wikiPages.createdById,
        updatedById: wikiPages.updatedById,
      })
      .from(wikiPages)
      .where(eq(wikiPages.channelId, channelId))
      .limit(1);

    if (!wiki) {
      // Return empty wiki
      return reply.send({
        data: {
          channelId,
          title: `${channel.name} Wiki`,
          content: "",
          version: 0,
          exists: false,
        },
      });
    }

    // Get creator info
    const [creator] = await db
      .select({ id: users.id, username: users.username, displayName: users.displayName })
      .from(users)
      .where(eq(users.id, wiki.createdById))
      .limit(1);

    // Get last updater info
    const [updater] = await db
      .select({ id: users.id, username: users.username, displayName: users.displayName })
      .from(users)
      .where(eq(users.id, wiki.updatedById))
      .limit(1);

    return reply.send({ data: { ...wiki, exists: true, createdBy: creator, updatedBy: updater } });
  });

  // PUT /api/v1/channels/:channelId/wiki - Update/create wiki page
  app.put("/channels/:channelId/wiki", async (request, reply) => {
    const db = (app as any).db;
    const redis = (app as any).redis;
    const { sub: userId } = request.user as { sub: string };
    const { channelId } = request.params as { channelId: string };
    const body = updateWikiSchema.parse(request.body);

    // Check channel exists
    const [channel] = await db
      .select()
      .from(channels)
      .where(eq(channels.id, channelId))
      .limit(1);

    if (!channel) {
      return reply.status(404).send({ error: "Channel not found", statusCode: 404 });
    }

    // Check workspace membership
    const [member] = await db
      .select()
      .from(workspaceMembers)
      .where(
        and(
          eq(workspaceMembers.workspaceId, channel.workspaceId),
          eq(workspaceMembers.userId, userId)
        )
      )
      .limit(1);

    if (!member) {
      return reply.status(403).send({ error: "Forbidden", statusCode: 403 });
    }

    // Check if wiki exists
    const [existing] = await db
      .select()
      .from(wikiPages)
      .where(eq(wikiPages.channelId, channelId))
      .limit(1);

    let wiki;
    const title = body.title || `${channel.name} Wiki`;

    if (existing) {
      // Save current version to history
      await db.insert(wikiPageHistory).values({
        id: nanoid(),
        wikiPageId: existing.id,
        title: existing.title,
        content: existing.content,
        version: existing.version,
        editedById: userId,
      });

      // Update wiki
      [wiki] = await db
        .update(wikiPages)
        .set({
          title,
          content: body.content,
          version: existing.version + 1,
          updatedById: userId,
          updatedAt: new Date(),
          isAutoGenerated: false,
        })
        .where(eq(wikiPages.id, existing.id))
        .returning();
    } else {
      // Create new wiki
      [wiki] = await db
        .insert(wikiPages)
        .values({
          id: nanoid(),
          channelId,
          title,
          content: body.content,
          version: 1,
          createdById: userId,
          updatedById: userId,
          isAutoGenerated: false,
        })
        .returning();
    }

    // Publish wiki update event
    if (redis) {
      await redis.publish(
        `channel:${channelId}`,
        JSON.stringify({
          type: "wiki:update",
          payload: {
            channelId,
            title: wiki.title,
            version: wiki.version,
            updatedBy: userId,
          },
          workspaceId: channel.workspaceId,
          timestamp: new Date().toISOString(),
        })
      );
    }

    return reply.send({ data: wiki });
  });

  // GET /api/v1/channels/:channelId/wiki/history - Get wiki version history
  app.get("/channels/:channelId/wiki/history", async (request, reply) => {
    const db = (app as any).db;
    const { sub: userId } = request.user as { sub: string };
    const { channelId } = request.params as { channelId: string };
    const { limit = 20, offset = 0 } = request.query as { limit?: number; offset?: number };

    // Check channel exists
    const [channel] = await db
      .select()
      .from(channels)
      .where(eq(channels.id, channelId))
      .limit(1);

    if (!channel) {
      return reply.status(404).send({ error: "Channel not found", statusCode: 404 });
    }

    // Check workspace membership
    const [member] = await db
      .select()
      .from(workspaceMembers)
      .where(
        and(
          eq(workspaceMembers.workspaceId, channel.workspaceId),
          eq(workspaceMembers.userId, userId)
        )
      )
      .limit(1);

    if (!member) {
      return reply.status(403).send({ error: "Forbidden", statusCode: 403 });
    }

    // Get wiki page
    const [wiki] = await db
      .select()
      .from(wikiPages)
      .where(eq(wikiPages.channelId, channelId))
      .limit(1);

    if (!wiki) {
      return reply.send({ data: [] });
    }

    // Get history
    const history = await db
      .select({
        id: wikiPageHistory.id,
        version: wikiPageHistory.version,
        title: wikiPageHistory.title,
        editedAt: wikiPageHistory.editedAt,
        editor: {
          id: users.id,
          username: users.username,
          displayName: users.displayName,
        },
      })
      .from(wikiPageHistory)
      .leftJoin(users, eq(wikiPageHistory.editedById, users.id))
      .where(eq(wikiPageHistory.wikiPageId, wiki.id))
      .orderBy(desc(wikiPageHistory.version))
      .limit(Math.min(Number(limit), 100))
      .offset(Number(offset));

    return reply.send({ data: history });
  });

  // GET /api/v1/channels/:channelId/wiki/history/:version - Get specific version
  app.get("/channels/:channelId/wiki/history/:version", async (request, reply) => {
    const db = (app as any).db;
    const { sub: userId } = request.user as { sub: string };
    const { channelId, version } = request.params as { channelId: string; version: string };

    // Check channel exists
    const [channel] = await db
      .select()
      .from(channels)
      .where(eq(channels.id, channelId))
      .limit(1);

    if (!channel) {
      return reply.status(404).send({ error: "Channel not found", statusCode: 404 });
    }

    // Check workspace membership
    const [member] = await db
      .select()
      .from(workspaceMembers)
      .where(
        and(
          eq(workspaceMembers.workspaceId, channel.workspaceId),
          eq(workspaceMembers.userId, userId)
        )
      )
      .limit(1);

    if (!member) {
      return reply.status(403).send({ error: "Forbidden", statusCode: 403 });
    }

    // Get wiki page
    const [wiki] = await db
      .select()
      .from(wikiPages)
      .where(eq(wikiPages.channelId, channelId))
      .limit(1);

    if (!wiki) {
      return reply.status(404).send({ error: "Wiki not found", statusCode: 404 });
    }

    // If requesting current version, return wiki
    if (Number(version) === wiki.version) {
      return reply.send({ data: wiki });
    }

    // Get historical version
    const [historyItem] = await db
      .select()
      .from(wikiPageHistory)
      .where(
        and(
          eq(wikiPageHistory.wikiPageId, wiki.id),
          eq(wikiPageHistory.version, Number(version))
        )
      )
      .limit(1);

    if (!historyItem) {
      return reply.status(404).send({ error: "Version not found", statusCode: 404 });
    }

    return reply.send({ data: historyItem });
  });

  // POST /api/v1/channels/:channelId/wiki/revert - Revert to specific version
  app.post("/channels/:channelId/wiki/revert", async (request, reply) => {
    const db = (app as any).db;
    const redis = (app as any).redis;
    const { sub: userId } = request.user as { sub: string };
    const { channelId } = request.params as { channelId: string };
    const { version } = z.object({ version: z.number().int().min(1) }).parse(request.body);

    // Check channel exists
    const [channel] = await db
      .select()
      .from(channels)
      .where(eq(channels.id, channelId))
      .limit(1);

    if (!channel) {
      return reply.status(404).send({ error: "Channel not found", statusCode: 404 });
    }

    // Check workspace membership (only admins can revert)
    const [member] = await db
      .select()
      .from(workspaceMembers)
      .where(
        and(
          eq(workspaceMembers.workspaceId, channel.workspaceId),
          eq(workspaceMembers.userId, userId)
        )
      )
      .limit(1);

    if (!member || !["owner", "admin"].includes(member.role)) {
      return reply.status(403).send({ error: "Admin required to revert", statusCode: 403 });
    }

    // Get wiki page
    const [wiki] = await db
      .select()
      .from(wikiPages)
      .where(eq(wikiPages.channelId, channelId))
      .limit(1);

    if (!wiki) {
      return reply.status(404).send({ error: "Wiki not found", statusCode: 404 });
    }

    // Get historical version
    const [historyItem] = await db
      .select()
      .from(wikiPageHistory)
      .where(
        and(
          eq(wikiPageHistory.wikiPageId, wiki.id),
          eq(wikiPageHistory.version, version)
        )
      )
      .limit(1);

    if (!historyItem) {
      return reply.status(404).send({ error: "Version not found", statusCode: 404 });
    }

    // Save current version to history
    await db.insert(wikiPageHistory).values({
      id: nanoid(),
      wikiPageId: wiki.id,
      title: wiki.title,
      content: wiki.content,
      version: wiki.version,
      editedById: userId,
    });

    // Update wiki with reverted content
    const [updated] = await db
      .update(wikiPages)
      .set({
        title: historyItem.title,
        content: historyItem.content,
        version: wiki.version + 1,
        updatedById: userId,
        updatedAt: new Date(),
      })
      .where(eq(wikiPages.id, wiki.id))
      .returning();

    // Publish update event
    if (redis) {
      await redis.publish(
        `channel:${channelId}`,
        JSON.stringify({
          type: "wiki:update",
          payload: {
            channelId,
            title: updated.title,
            version: updated.version,
            updatedBy: userId,
            reverted: true,
            revertedFrom: version,
          },
          workspaceId: channel.workspaceId,
          timestamp: new Date().toISOString(),
        })
      );
    }

    return reply.send({ data: updated });
  });
}
